In [168]:
import pandas as pd

In [ ]:
# 코스피 200 기업 뽑아내기

In [169]:
a="대림산업 대우건설 동양 삼성엔지니어링 쌍용양회 아이에스동서 한일홀딩스 한전기술 현대건설 GS건설 HDC HDC현대산업개발 KCC LG하우시스 기업은행 메리츠종금증권 미래에셋대우 삼성생명 삼성증권 삼성카드 삼성화재 신한지주 우리금융지주 하나금융지주 한국금융지주 한화생명 현대해상 BNK금융지주 DB손해보험 KB금융 NH투자증권 강원랜드 금호타이어 기아차 넥센타이어 대교 롯데쇼핑 롯데하이마트 만도 삼성물산 세방전지 신세계 쌍용차 에스엘 영원무역 코웨이 쿠쿠홀딩스 한국타이어 한국타이어월드와이드 한라홀딩스 한샘 한섬 한세실업 한온시스템 현대리바트 현대모비스 현대백화점 현대위아 현대차 현대홈쇼핑 호텔신라 GKL LF S&T모티브 SK네트웍스 대한항공 두산 에스원 팬오션 포스코대우 한국단자 한국항공우주 한전KPS 한화에어로스페이스 현대글로비스 CJ대한통운 LG상사 LIG넥스원 LS LS산전 남양유업 농심 대상 동서 동원F&B 락앤락 롯데지주 롯데칠성 롯데푸드 무학 빙그레 삼양사 삼양홀딩스 아모레G 아모레퍼시픽 오뚜기 오리온 오리온홀딩스 이마트 코스맥스 팜스코 하이트진로 한국가스공사 한국전력 한국콜마 현대그린푸드 BGF BGF리테일 CJ CJ제일제당 GS리테일 KT&G LG생활건강 SPC삼립 금호석유 남해화학 대한유화 롯데케미칼 롯데정밀화학 유니드 코오롱인더 태광산업 한국쉘석유 한솔케미칼 한화 한화케미칼 효성 효성중공업 후성 휴켐스 AK홀딩스 GS LG화학 OCI S-Oil SK SKC SK디스커버리 SK이노베이션 SK케미칼 대덕전자 삼성SDI 삼성SDS 삼성전기 삼성전자 일진머티리얼즈 DB하이텍 LG LG디스플레이 LG이노텍 SK하이닉스 대우조선해양 두산인프라코어 두산밥캣 두산중공업 삼성중공업 한진중공업 현대로템 현대미포조선 현대엘리베이터 현대중공업 현대중공업지주 고려아연 고려제강 동국제강 동원시스템즈 세아베스틸 영풍 풍산 현대제철 POSCO 넷마블 엔씨소프트 이노션 제일기획 카카오 CJ CGV KT LG유플러스 NAVER SBS SK텔레콤 녹십자 녹십자홀딩스 대웅제약 동아쏘시오홀딩스 동아에스티 보령제약 부광약품 삼성바이오로직스 셀트리온 영진약품 유한양행 일양약품 종근당 한미사이언스 한미약품 한올바이오파마 JW중외제약 JW홀딩스"
b =a.split(" ")
b

['대림산업',
 '대우건설',
 '동양',
 '삼성엔지니어링',
 '쌍용양회',
 '아이에스동서',
 '한일홀딩스',
 '한전기술',
 '현대건설',
 'GS건설',
 'HDC',
 'HDC현대산업개발',
 'KCC',
 'LG하우시스',
 '기업은행',
 '메리츠종금증권',
 '미래에셋대우',
 '삼성생명',
 '삼성증권',
 '삼성카드',
 '삼성화재',
 '신한지주',
 '우리금융지주',
 '하나금융지주',
 '한국금융지주',
 '한화생명',
 '현대해상',
 'BNK금융지주',
 'DB손해보험',
 'KB금융',
 'NH투자증권',
 '강원랜드',
 '금호타이어',
 '기아차',
 '넥센타이어',
 '대교',
 '롯데쇼핑',
 '롯데하이마트',
 '만도',
 '삼성물산',
 '세방전지',
 '신세계',
 '쌍용차',
 '에스엘',
 '영원무역',
 '코웨이',
 '쿠쿠홀딩스',
 '한국타이어',
 '한국타이어월드와이드',
 '한라홀딩스',
 '한샘',
 '한섬',
 '한세실업',
 '한온시스템',
 '현대리바트',
 '현대모비스',
 '현대백화점',
 '현대위아',
 '현대차',
 '현대홈쇼핑',
 '호텔신라',
 'GKL',
 'LF',
 'S&T모티브',
 'SK네트웍스',
 '대한항공',
 '두산',
 '에스원',
 '팬오션',
 '포스코대우',
 '한국단자',
 '한국항공우주',
 '한전KPS',
 '한화에어로스페이스',
 '현대글로비스',
 'CJ대한통운',
 'LG상사',
 'LIG넥스원',
 'LS',
 'LS산전',
 '남양유업',
 '농심',
 '대상',
 '동서',
 '동원F&B',
 '락앤락',
 '롯데지주',
 '롯데칠성',
 '롯데푸드',
 '무학',
 '빙그레',
 '삼양사',
 '삼양홀딩스',
 '아모레G',
 '아모레퍼시픽',
 '오뚜기',
 '오리온',
 '오리온홀딩스',
 '이마트',
 '코스맥스',
 '팜스코',
 '하이트진로',
 '한국가스공사',
 '한국전력',
 '한국콜마',
 '현대그린푸드',
 'BGF',
 'BGF리테일',
 'CJ',
 'CJ제일제당',
 'GS리테일',
 'KT&G',
 'LG생활건강',
 'SPC삼립',
 '금호석유',
 '남해화학',
 '대한유화',
 '롯데케미칼',
 '롯데정밀화학',
 '유니드',
 '코오롱인더',
 '태광산업',
 '한국쉘석유',
 '한솔케미칼',
 '한화',
 '한화케미칼',
 '효성',
 '효성중공업',
 '후성',
 '휴켐스',
 'AK홀딩스',
 'GS',
 'LG화학',
 'OCI',
 'S-Oil',
 'SK',
 'SKC',
 'SK디스커버리',
 'SK이노베이션',
 'SK케미칼',
 '대덕전자',
 '삼성SDI',
 '삼성SDS',
 '삼성전기',
 '삼성전자',
 '일진머티리얼즈',
 'DB하이텍',
 'LG',
 'LG디스플레이',
 'LG이노텍',
 'SK하이닉스',
 '대우조선해양',
 '두산인프라코어',
 '두산밥캣',
 '두산중공업',
 '삼성중공업',
 '한진중공업',
 '현대로템',
 '현대미포조선',
 '현대엘리베이터',
 '현대중공업',
 '현대중공업지주',
 '고려아연',
 '고려제강',
 '동국제강',
 '동원시스템즈',
 '세아베스틸',
 '영풍',
 '풍산',
 '현대제철',
 'POSCO',
 '넷마블',
 '엔씨소프트',
 '이노션',
 '제일기획',
 '카카오',
 'CJ',
 'CGV',
 'KT',
 'LG유플러스',
 'NAVER',
 'SBS',
 'SK텔레콤',
 '녹십자',
 '녹십자홀딩스',
 '대웅제약',
 '동아쏘시오홀딩스',
 '동아에스티',
 '보령제약',
 '부광약품',
 '삼성바이오로직스',
 '셀트리온',
 '영진약품',
 '유한양행',
 '일양약품',
 '종근당',
 '한미사이언스',
 '한미약품',
 '한올바이오파마',
 'JW중외제약',
 'JW홀딩스']

In [ ]:
# 주가 자료 불러오기

In [170]:
df1 = pd.read_csv(r"C:\Users\deokju.DESKTOP-SSNCOJV\Desktop/주가.csv", engine='python')

In [18]:
df1.head(20)

,itemcode,itemname,market,date,close_val,change_val,change_rate,acc_quant,market_sum
0,3280,흥아해운,KOSPI,20150107,2805.0,-45.0,-1.60,1470322.0,2376.0
1,3280,흥아해운,KOSPI,20150113,2655.0,-25.0,-0.94,1754300.0,2249.0
2,3280,흥아해운,KOSPI,20150116,2710.0,105.0,3.87,2449216.0,2295.0
3,3280,흥아해운,KOSPI,20150119,2575.0,-135.0,-5.24,2512566.0,2181.0
4,3280,흥아해운,KOSPI,20150122,2570.0,-35.0,-1.36,1638534.0,2177.0
5,3280,흥아해운,KOSPI,20150128,2700.0,20.0,0.74,1226866.0,2287.0
6,3280,흥아해운,KOSPI,20150203,2800.0,25.0,0.89,1137256.0,2371.0
7,3280,흥아해운,KOSPI,20150206,2770.0,-20.0,-0.72,644219.0,2346.0
8,3280,흥아해운,KOSPI,20150209,2845.0,75.0,2.64,1601841.0,2410.0
9,3280,흥아해운,KOSPI,20150212,2980.0,30.0,1.01,2162251.0,2524.0
10,3280,흥아해운,KOSPI,20150224,2890.0,110.0,3.81,1050517.0,2448.0
11,3280,흥아해운,KOSPI,20150227,2890.0,-10.0,-0.35,3342322.0,2448.0
12,3280,흥아해운,KOSPI,20150302,2855.0,-35.0,-1.23,1458196.0,2418.0
13,3280,흥아해운,KOSPI,20150305,3485.0,440.0,12.63,10933682.0,2952.0
14,3280,흥아해운,KOSPI,20150311,3310.0,90.0,2.72,1338222.0,2804.0
15,3280,흥아해운,KOSPI,20150317,3500.0,-70.0,-2.00,1543252.0,2964.0
16,3280,흥아해운,KOSPI,20150320,3575.0,10.0,0.28,973474.0,3028.0
17,3280,흥아해운,KOSPI,20150323,3450.0,-125.0,-3.62,1221425.0,2922.0
18,3280,흥아해운,KOSPI,20150326,3570.0,-105.0,-2.94,1172665.0,3024.0
19,3280,흥아해운,KOSPI,20150401,3820.0,20.0,0.52,968353.0,3236.0

In [171]:
df=df1[df1['itemname'].isin(b)] # itemname 열에서 blist에 있는 회사만 출력(kospi200만 출력)

In [ ]:
# null 값 확인

In [172]:
df.isnull().any()

itemcode       False
itemname       False
market         False
date           False
close_val       True
change_val      True
change_rate     True
acc_quant       True
market_sum      True
dtype: bool

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60619 entries, 1292 to 270782
Data columns (total 9 columns):
itemcode       60619 non-null object
itemname       60619 non-null object
market         60619 non-null object
date           60619 non-null int64
close_val      60614 non-null float64
change_val     57233 non-null float64
change_rate    57233 non-null float64
acc_quant      60376 non-null float64
market_sum     60614 non-null float64
dtypes: float64(5), int64(1), object(3)
memory usage: 4.6+ MB

In [174]:
df = df.loc[ : ,'itemname':'change_rate']
df

       itemname market      date  close_val  change_val  change_rate
1292        휴켐스  KOSPI  20150107    25550.0      -200.0        -0.78
1293        휴켐스  KOSPI  20150113    25200.0     -1300.0        -5.16
1294        휴켐스  KOSPI  20150116    26800.0       350.0         1.31
1295        휴켐스  KOSPI  20150119    27050.0       250.0         0.92
1296        휴켐스  KOSPI  20150122    26800.0      -250.0        -0.93
1297        휴켐스  KOSPI  20150128    26650.0       150.0         0.56
1298        휴켐스  KOSPI  20150203    26100.0      -300.0        -1.15
1299        휴켐스  KOSPI  20150206    26200.0      -100.0        -0.38
1300        휴켐스  KOSPI  20150209    26100.0      -100.0        -0.38
1301        휴켐스  KOSPI  20150212    25900.0      -300.0        -1.16
1302        휴켐스  KOSPI  20150224    26100.0       300.0         1.15
1303        휴켐스  KOSPI  20150227    25650.0       150.0         0.58
1304        휴켐스  KOSPI  20150302    25400.0      -250.0        -0.98
1305        휴켐스  KOSPI  20150305    25750.0       300.0         1.17
1306        휴켐스  KOSPI  20150311    24950.0      -600.0        -2.40
1307        휴켐스  KOSPI  20150317    25000.0      -400.0        -1.60
1308        휴켐스  KOSPI  20150320    24850.0         NaN          NaN
1309        휴켐스  KOSPI  20150323    24900.0        50.0         0.20
1310        휴켐스  KOSPI  20150326    25450.0       550.0         2.16
1311        휴켐스  KOSPI  20150401    25650.0       100.0         0.39
1312        휴켐스  KOSPI  20150407    26450.0       150.0         0.57
1313        휴켐스  KOSPI  20150410    26300.0      -150.0        -0.57
1314        휴켐스  KOSPI  20150413    26100.0      -200.0        -0.77
1315        휴켐스  KOSPI  20150416    26150.0      -350.0        -1.34
1316        휴켐스  KOSPI  20150422    25350.0      -150.0        -0.59
1317        휴켐스  KOSPI  20150428    25600.0      -150.0        -0.59
1318        휴켐스  KOSPI  20150506    26400.0      -150.0        -0.57
1319        휴켐스  KOSPI  20150512    28150.0       300.0         1.07
1320        휴켐스  KOSPI  20150515    26600.0      -150.0        -0.56
1321        휴켐스  KOSPI  20150518    26550.0       -50.0        -0.19
...         ...    ...       ...        ...         ...          ...
270753    AK홀딩스  KOSPI  20180821    70500.0      -500.0        -0.71
270754    AK홀딩스  KOSPI  20180824    67200.0      -700.0        -1.04
270755    AK홀딩스  KOSPI  20180827    67200.0         NaN          NaN
270756    AK홀딩스  KOSPI  20180830    66000.0     -1000.0        -1.52
270757    AK홀딩스  KOSPI  20180905    66000.0       700.0         1.06
270758    AK홀딩스  KOSPI  20180911    61600.0      -100.0        -0.16
270759    AK홀딩스  KOSPI  20180914    64300.0      1900.0         2.95
270760    AK홀딩스  KOSPI  20180917    63300.0     -1000.0        -1.58
270761    AK홀딩스  KOSPI  20180920    60600.0     -1200.0        -1.98
270762    AK홀딩스  KOSPI  20181001    59500.0     -1700.0        -2.86
270763    AK홀딩스  KOSPI  20181004    57800.0      -900.0        -1.56
270764    AK홀딩스  KOSPI  20181010    52800.0     -2600.0        -4.92
270765    AK홀딩스  KOSPI  20181016    50400.0      -400.0        -0.79
270766    AK홀딩스  KOSPI  20181019    47550.0       100.0         0.21
270767    AK홀딩스  KOSPI  20181022    46650.0      -900.0        -1.93
270768    AK홀딩스  KOSPI  20181025    45800.0      -300.0        -0.66
270769    AK홀딩스  KOSPI  20181031    44600.0      1000.0         2.24
270770    AK홀딩스  KOSPI  20181106    46750.0      1300.0         2.78
270771    AK홀딩스  KOSPI  20181109    46650.0     -1000.0        -2.14
270772    AK홀딩스  KOSPI  20181112    47100.0       450.0         0.96
270773    AK홀딩스  KOSPI  20181115    48650.0       950.0         1.95
270774    AK홀딩스  KOSPI  20181121    51500.0      2350.0         4.56
270775    AK홀딩스  KOSPI  20181127    52400.0      -100.0        -0.19
270776    AK홀딩스  KOSPI  20181130    53200.0       600.0         1.13
270777    AK홀딩스  KOSPI  20181205    53900.0     -1000.0        -1.86
270778    AK홀딩스  KOSPI  20181211    55100.0      -700.0        -1.27
270779    AK홀딩스  KOSPI  20181214    55900.0         NaN          NaN
270780    AK홀딩스  KOSPI  20181217    56500.0       600.0         1.06
270781    AK홀딩스  KOSPI  20181220    56200.0      -100.0        -0.18
270782    AK홀딩스  KOSPI  20181226    53600.0      -700.0        -1.31

[60619 rows x 6 columns]

In [ ]:
# 정리 후 한번 저장

In [199]:
df.to_csv('out.csv')

In [200]:
man=pd.read_csv(r"C:\Users\deokju.DESKTOP-SSNCOJV\Desktop/out.csv", engine='python')
man.info()
man.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60619 entries, 0 to 60618
Data columns (total 6 columns):
itemname       59109 non-null object
market         59109 non-null object
date           59109 non-null float64
close_val      59109 non-null float64
change_val     55798 non-null float64
change_rate    55798 non-null float64
dtypes: float64(4), object(2)
memory usage: 2.8+ MB

  itemname market        date  close_val  change_val  change_rate
0      휴켐스  KOSPI  20150107.0    25550.0      -200.0        -0.78
1      휴켐스  KOSPI  20150113.0    25200.0     -1300.0        -5.16
2      휴켐스  KOSPI  20150116.0    26800.0       350.0         1.31
3      휴켐스  KOSPI  20150119.0    27050.0       250.0         0.92
4      휴켐스  KOSPI  20150122.0    26800.0      -250.0        -0.93

In [1]:
# 주식 종목 별로 묶어서 같은 기간 동안 코스피200에 존재 했는지 확인

In [203]:
man.groupby("itemname").count()
man.groupby("itemname").count()[1:50]
man.groupby("itemname").count()[51:100]
man.groupby("itemname").count()[101:150]
man.groupby("itemname").count()[151:200]
t = ["BGF리테일","HDC현대산업개발","현대중공업지주","효성중공업","LIG넥스원","SK케미칼","넷마블","두산밥캣","이노션","삼성바이오로직스","오리온"]

           market  date  close_val  change_val  change_rate
itemname
AK홀딩스         323   323        323         310          310
BGF           323   323        323         294          294
BNK금융지주       323   323        323         300          300
CJ            323   323        323         303          303
CJ대한통운        323   323        323         291          291
CJ제일제당        323   323        323         310          310
DB손해보험        323   323        323         310          310
DB하이텍         323   323        323         304          304
GKL           323   323        323         303          303
GS            323   323        323         309          309
GS건설          323   323        323         309          309
GS리테일         323   323        323         307          307
HDC           323   323        323         298          298
JW중외제약        323   323        323         310          310
JW홀딩스         323   323        323         317          317
KB금융          323   323        323         310          310
KCC           323   323        323         306          306
KT            323   323        323         295          295
KT&G          323   323        323         289          289
LF            323   323        323         294          294
LG            323   323        323         307          307
LG디스플레이       323   323        323         307          307
LG상사          323   323        323         309          309
LG생활건강        323   323        323         313          313
LG유플러스        323   323        323         293          293
LG이노텍         323   323        323         307          307
LG하우시스        323   323        323         305          305
LG화학          323   323        323         308          308
LS            323   323        323         315          315
LS산전          323   323        323         304          304
...           ...   ...        ...         ...          ...
한세실업          323   323        323         306          306
한솔케미칼         323   323        323         312          312
한온시스템         323   323        323         306          306
한올바이오파마       323   323        323         311          311
한일홀딩스         323   323        323         297          297
한전KPS         323   323        323         311          311
한전기술          323   323        323         307          307
한진중공업         323   323        323         317          317
한화            323   323        323         308          308
한화생명          323   323        323         309          309
한화에어로스페이스     323   323        323         316          316
한화케미칼         323   323        323         304          304
현대건설          323   323        323         308          308
현대그린푸드        323   323        323         295          295
현대글로비스        323   323        323         304          304
현대로템          323   323        323         306          306
현대리바트         323   323        323         312          312
현대모비스         323   323        323         299          299
현대미포조선        323   323        323         314          314
현대백화점         323   323        323         299          299
현대위아          323   323        323         304          304
현대제철          323   323        323         309          309
현대중공업         323   323        323         295          295
현대차           323   323        323         294          294
현대해상          323   323        323         309          309
현대홈쇼핑         323   323        323         296          296
호텔신라          323   323        323         299          299
효성            323   323        323         295          295
후성            323   323        323         310          310
휴켐스           323   323        323         297          297

[183 rows x 5 columns]

          market  date  close_val  change_val  change_rate
itemname
BGF          323   323        323         294          294
BNK금융지주      323   323        323         300          300
CJ           323   323        323         303          303
CJ대한통운       323   323        323         291          291
CJ제일제당       323   323        323         310          310
DB손해보험       323   323        323         310          310
DB하이텍        323   323        323         304          304
GKL          323   323        323         303          303
GS           323   323        323         309          309
GS건설         323   323        323         309          309
GS리테일        323   323        323         307          307
HDC          323   323        323         298          298
JW중외제약       323   323        323         310          310
JW홀딩스        323   323        323         317          317
KB금융         323   323        323         310          310
KCC          323   323        323         306          306
KT           323   323        323         295          295
KT&G         323   323        323         289          289
LF           323   323        323         294          294
LG           323   323        323         307          307
LG디스플레이      323   323        323         307          307
LG상사         323   323        323         309          309
LG생활건강       323   323        323         313          313
LG유플러스       323   323        323         293          293
LG이노텍        323   323        323         307          307
LG하우시스       323   323        323         305          305
LG화학         323   323        323         308          308
LS           323   323        323         315          315
LS산전         323   323        323         304          304
NAVER        323   323        323         306          306
NH투자증권       323   323        323         295          295
OCI          323   323        323         304          304
POSCO        323   323        323         306          306
S&T모티브       323   323        323         306          306
S-Oil        323   323        323         302          302
SBS          323   323        323         303          303
SK           323   323        323         304          304
SKC          323   323        323         312          312
SK네트웍스       323   323        323         313          313
SK디스커버리      323   323        323         298          298
SK이노베이션      323   323        323         305          305
SK텔레콤        323   323        323         305          305
SK하이닉스       323   323        323         305          305
SPC삼립        323   323        323         299          299
강원랜드         323   323        323         303          303
고려아연         323   323        323         306          306
고려제강         323   323        323         302          302
금호석유         323   323        323         313          313
금호타이어        323   323        323         307          307

          market  date  close_val  change_val  change_rate
itemname
기업은행         323   323        323         284          284
남양유업         323   323        323         308          308
남해화학         323   323        323         302          302
넥센타이어        323   323        323         287          287
녹십자          323   323        323         299          299
녹십자홀딩스       323   323        323         307          307
농심           323   323        323         310          310
대교           323   323        323         305          305
대덕전자         323   323        323         306          306
대림산업         323   323        323         311          311
대상           323   323        323         312          312
대우건설         323   323        323         313          313
대우조선해양       323   323        323         275          275
대웅제약         323   323        323         312          312
대한유화         323   323        323         307          307
대한항공         323   323        323         310          310
동국제강         323   323        323         304          304
동서           323   323        323         301          301
동아쏘시오홀딩스     323   323        323         297          297
동아에스티        323   323        323         308          308
동양           323   323        323         294          294
동원F&B        323   323        323         310          310
동원시스템즈       323   323        323         309          309
두산           323   323        323         304          304
두산인프라코어      323   323        323         316          316
두산중공업        323   323        323         308          308
락앤락          323   323        323         303          303
롯데쇼핑         323   323        323         296          296
롯데정밀화학       323   323        323         315          315
롯데지주         323   323        323         306          306
롯데칠성         323   323        323         310          310
롯데케미칼        323   323        323         308          308
롯데푸드         323   323        323         307          307
롯데하이마트       323   323        323         306          306
만도           323   323        323         306          306
메리츠종금증권      323   323        323         308          308
무학           323   323        323         306          306
미래에셋대우       323   323        323         303          303
보령제약         323   323        323         304          304
부광약품         323   323        323         314          314
빙그레          323   323        323         311          311
삼성SDI        323   323        323         297          297
삼성물산         323   323        323         289          289
삼성생명         323   323        323         289          289
삼성엔지니어링      323   323        323         297          297
삼성전기         323   323        323         307          307
삼성전자         323   323        323         311          311
삼성중공업        323   323        323         307          307
삼성증권         323   323        323         304          304

            market  date  close_val  change_val  change_rate
itemname
삼성화재           323   323        323         306          306
삼양사            323   323        323         306          306
삼양홀딩스          323   323        323         299          299
세방전지           323   323        323         310          310
세아베스틸          323   323        323         308          308
셀트리온           323   323        323         307          307
신세계            323   323        323         308          308
신한지주           323   323        323         312          312
쌍용양회           323   323        323         303          303
쌍용차            323   323        323         311          311
아모레G           323   323        323         299          299
아모레퍼시픽         323   323        323         305          305
아이에스동서         323   323        323         306          306
에스엘            323   323        323         304          304
에스원            323   323        323         304          304
엔씨소프트          323   323        323         313          313
영원무역           323   323        323         307          307
영진약품           323   323        323         314          314
영풍             323   323        323         309          309
오뚜기            323   323        323         312          312
오리온홀딩스         323   323        323         302          302
유니드            323   323        323         302          302
유한양행           323   323        323         299          299
이마트            323   323        323         300          300
일양약품           323   323        323         311          311
일진머티리얼즈        323   323        323         307          307
제일기획           323   323        323         295          295
종근당            323   323        323         308          308
카카오            323   323        323         307          307
코스맥스           323   323        323         302          302
코오롱인더          323   323        323         307          307
쿠쿠홀딩스          323   323        323         295          295
태광산업           323   323        323         305          305
팜스코            323   323        323         286          286
팬오션            323   323        323         303          303
풍산             323   323        323         317          317
하나금융지주         323   323        323         309          309
하이트진로          323   323        323         306          306
한국가스공사         323   323        323         314          314
한국금융지주         323   323        323         311          311
한국단자           323   323        323         299          299
한국쉘석유          323   323        323         294          294
한국전력           323   323        323         307          307
한국콜마           323   323        323         313          313
한국타이어          323   323        323         304          304
한국타이어월드와이드     323   323        323         302          302
한국항공우주         323   323        323         312          312
한라홀딩스          323   323        323         304          304
한미사이언스         323   323        323         309          309

           market  date  close_val  change_val  change_rate
itemname
한샘            323   323        323         307          307
한섬            323   323        323         303          303
한세실업          323   323        323         306          306
한솔케미칼         323   323        323         312          312
한온시스템         323   323        323         306          306
한올바이오파마       323   323        323         311          311
한일홀딩스         323   323        323         297          297
한전KPS         323   323        323         311          311
한전기술          323   323        323         307          307
한진중공업         323   323        323         317          317
한화            323   323        323         308          308
한화생명          323   323        323         309          309
한화에어로스페이스     323   323        323         316          316
한화케미칼         323   323        323         304          304
현대건설          323   323        323         308          308
현대그린푸드        323   323        323         295          295
현대글로비스        323   323        323         304          304
현대로템          323   323        323         306          306
현대리바트         323   323        323         312          312
현대모비스         323   323        323         299          299
현대미포조선        323   323        323         314          314
현대백화점         323   323        323         299          299
현대위아          323   323        323         304          304
현대제철          323   323        323         309          309
현대중공업         323   323        323         295          295
현대차           323   323        323         294          294
현대해상          323   323        323         309          309
현대홈쇼핑         323   323        323         296          296
호텔신라          323   323        323         299          299
효성            323   323        323         295          295
후성            323   323        323         310          310
휴켐스           323   323        323         297          297

In [193]:
df=df.drop(("BGF리테일","HDC현대산업개발","현대중공업지주","효성중공업","LIG넥스원","SK케미칼","넷마블","두산밥캣","이노션")

SyntaxError: unexpected EOF while parsing (<ipython-input-193-bf7ab3e79bbb>, line 1)

In [205]:
# change_rate 100씩 더해 기하평균 가능하게 만들기

In [204]:
man["change_rate +100"] = man["change_rate"] + 100

In [215]:
man3=pd.read_csv(r"C:\Users\deokju.DESKTOP-SSNCOJV\Desktop/out2.csv", engine='python')

In [216]:
man3

,itemname,market,date,close_val,change_val,change_rate,change_rate +100
0,AK홀딩스,KOSPI,20150107,86600,-2000.000000,-2.310000,97.690000
1,AK홀딩스,KOSPI,20150113,88000,-1000.000000,-1.140000,98.860000
2,AK홀딩스,KOSPI,20150116,92300,300.000000,0.330000,100.330000
3,AK홀딩스,KOSPI,20150119,88200,-4100.000000,-4.650000,95.350000
4,AK홀딩스,KOSPI,20150122,90300,-1000.000000,-1.110000,98.890000
5,AK홀딩스,KOSPI,20150128,92400,-100.000000,-0.110000,99.890000
6,AK홀딩스,KOSPI,20150203,98000,-34.516129,-0.050871,99.949129
7,AK홀딩스,KOSPI,20150206,91700,-1700.000000,-1.850000,98.150000
8,AK홀딩스,KOSPI,20150209,86000,-5700.000000,-6.630000,93.370000
9,AK홀딩스,KOSPI,20150212,91500,1600.000000,1.750000,101.750000
10,AK홀딩스,KOSPI,20150224,99800,12000.000000,12.020000,112.020000
11,AK홀딩스,KOSPI,20150227,101000,500.000000,0.500000,100.500000
12,AK홀딩스,KOSPI,20150302,102500,1500.000000,1.460000,101.460000
13,AK홀딩스,KOSPI,20150305,100000,1600.000000,1.600000,101.600000
14,AK홀딩스,KOSPI,20150311,92800,200.000000,0.220000,100.220000
15,AK홀딩스,KOSPI,20150317,98700,-3800.000000,-3.850000,96.150000
16,AK홀딩스,KOSPI,20150320,96000,1000.000000,1.040000,101.040000
17,AK홀딩스,KOSPI,20150323,96000,-34.516129,-0.050871,99.949129
18,AK홀딩스,KOSPI,20150326,91300,-2600.000000,-2.850000,97.150000
19,AK홀딩스,KOSPI,20150401,98500,300.000000,0.300000,100.300000
20,AK홀딩스,KOSPI,20150407,94700,-2500.000000,-2.640000,97.360000
21,AK홀딩스,KOSPI,20150410,90600,-700.000000,-0.770000,99.230000
22,AK홀딩스,KOSPI,20150413,92100,1500.000000,1.630000,101.630000
23,AK홀딩스,KOSPI,20150416,89100,-2000.000000,-2.240000,97.760000
24,AK홀딩스,KOSPI,20150422,88300,-1300.000000,-1.470000,98.530000
25,AK홀딩스,KOSPI,20150428,88300,-1800.000000,-2.040000,97.960000
26,AK홀딩스,KOSPI,20150506,79000,-2000.000000,-2.530000,97.470000
27,AK홀딩스,KOSPI,20150512,82800,800.000000,0.970000,100.970000
28,AK홀딩스,KOSPI,20150515,84900,3700.000000,4.360000,104.360000
29,AK홀딩스,KOSPI,20150518,85000,100.000000,0.120000,100.120000
...,...,...,...,...,...,...,...
59079,휴켐스,KOSPI,20180821,26500,750.000000,2.830000,102.830000
59080,휴켐스,KOSPI,20180824,25500,100.000000,0.390000,100.390000
59081,휴켐스,KOSPI,20180827,25500,-10.101010,-0.064579,99.935421
59082,휴켐스,KOSPI,20180830,25050,-400.000000,-1.600000,98.400000
59083,휴켐스,KOSPI,20180905,24950,-50.000000,-0.200000,99.800000
59084,휴켐스,KOSPI,20180911,24800,50.000000,0.200000,100.200000
59085,휴켐스,KOSPI,20180914,25050,150.000000,0.600000,100.600000
59086,휴켐스,KOSPI,20180917,24450,-600.000000,-2.450000,97.550000
59087,휴켐스,KOSPI,20180920,23950,-150.000000,-0.630000,99.370000
59088,휴켐스,KOSPI,20181001,24700,-250.000000,-1.010000,98.990000
59089,휴켐스,KOSPI,20181004,24150,-400.000000,-1.660000,98.340000
59090,휴켐스,KOSPI,20181010,24150,100.000000,0.410000,100.410000
59091,휴켐스,KOSPI,20181016,23400,-600.000000,-2.560000,97.440000
59092,휴켐스,KOSPI,20181019,23700,200.000000,0.840000,100.840000
59093,휴켐스,KOSPI,20181022,23200,-500.000000,-2.160000,97.840000
59094,휴켐스,KOSPI,20181025,23250,250.000000,1.080000,101.080000
59095,휴켐스,KOSPI,20181031,21800,500.000000,2.290000,102.290000
59096,휴켐스,KOSPI,20181106,22700,800.000000,3.520000,103.520000
59097,휴켐스,KOSPI,20181109,22850,200.000000,0.880000,100.880000
59098,휴켐스,KOSPI,20181112,23100,250.000000,1.080000,101.080000
59099,휴켐스,KOSPI,20181115,23100,-50.000000,-0.220000,99.780000
59100,휴켐스,KOSPI,20181121,25100,500.000000,1.990000,101.990000
59101,휴켐스,KOSPI,20181127,25550,700.000000,2.740000,102.740000
59102,휴켐스,KOSPI,20181130,26200,1150.000000,4.390000,104.390000
59103,휴켐스,KOSPI,20181205,25150,300.000000,1.190000,101.190000
59104,휴켐스,KOSPI,20181211,25100,-10.101010,-0.064579,99.935421
59105,휴켐스,KOSPI,20181214,25700,400.000000,1.560000,101.560000
59106,휴켐스,KOSPI,20181217,25000,-700.000000,-2.800000,97.200000
59107,휴켐스,KOSPI,20181220,25900,250.000000,0.970000,100.970000
59108,휴켐스,KOSPI,20181226,26600,300.000000,1.130000,101.130000

In [214]:
# 코스피200을 종목 별로 묶기

In [218]:
one=['대림산업',
 '대우건설',
 '동양',
 '삼성엔지니어링',
 '쌍용양회',
 '아이에스동서',
 '한일홀딩스',
 '한전기술',
 '현대건설',
 'GS건설',
 'HDC',
 'HDC현대산업개발',
 'KCC',
 'LG하우시스']
two=['기업은행',
 '메리츠종금증권',
 '미래에셋대우',
 '삼성생명',
 '삼성증권',
 '삼성카드',
 '삼성화재',
 '신한지주',
 '우리금융지주',
 '하나금융지주',
 '한국금융지주',
 '한화생명',
 '현대해상',
 'BNK금융지주',
 'DB손해보험',
 'KB금융',
 'NH투자증권',
]
three=[ '강원랜드',
 '금호타이어',
 '기아차',
 '넥센타이어',
 '대교',
 '롯데쇼핑',
 '롯데하이마트',
 '만도',
 '삼성물산',
 '세방전지',
 '신세계',
 '쌍용차',
 '에스엘',
 '영원무역',
 '코웨이',
 '쿠쿠홀딩스',
 '한국타이어',
 '한국타이어월드와이드',
 '한라홀딩스',
 '한샘',
 '한섬',
 '한세실업',
 '한온시스템',
 '현대리바트',
 '현대모비스',
 '현대백화점',
 '현대위아',
 '현대차',
 '현대홈쇼핑',
 '호텔신라',
 'GKL',
 'LF',
 'S&T모티브',
 'SK네트웍스']
four=['대한항공',
 '두산',
 '에스원',
 '팬오션',
 '포스코대우',
 '한국단자',
 '한국항공우주',
 '한전KPS',
 '한화에어로스페이스',
 '현대글로비스',
 'CJ대한통운',
 'LG상사',
 'LIG넥스원',
 'LS',
 'LS산전']
five=[ '남양유업',
 '농심',
 '대상',
 '동서',
 '동원F&B',
 '락앤락',
 '롯데지주',
 '롯데칠성',
 '롯데푸드',
 '무학',
 '빙그레',
 '삼양사',
 '삼양홀딩스',
 '아모레G',
 '아모레퍼시픽',
 '오뚜기',
 '오리온',
 '오리온홀딩스',
 '이마트',
 '코스맥스',
 '팜스코',
 '하이트진로',
 '한국가스공사',
 '한국전력',
 '한국콜마',
 '현대그린푸드',
 'BGF',
 'BGF리테일',
 'CJ',
 'CJ제일제당',
 'GS리테일',
 'KT&G',
 'LG생활건강',
 'SPC삼립']
six =[ '금호석유',
 '남해화학',
 '대한유화',
 '롯데케미칼',
 '롯데정밀화학',
 '유니드',
 '코오롱인더',
 '태광산업',
 '한국쉘석유',
 '한솔케미칼',
 '한화',
 '한화케미칼',
 '효성',
 '효성중공업',
 '후성',
 '휴켐스',
 'AK홀딩스',
 'GS',
 'LG화학',
 'OCI',
 'S-Oil',
 'SK',
 'SKC',
 'SK디스커버리',
 'SK이노베이션',
 'SK케미칼']
seven=['대덕전자',
 '삼성SDI',
 '삼성SDS',
 '삼성전기',
 '삼성전자',
 '일진머티리얼즈',
 'DB하이텍',
 'LG',
 'LG디스플레이',
 'LG이노텍',
 'SK하이닉스']
eight=['대우조선해양',
 '두산인프라코어',
 '두산밥캣',
 '두산중공업',
 '삼성중공업',
 '한진중공업',
 '현대로템',
 '현대미포조선',
 '현대엘리베이터',
 '현대중공업',
 '현대중공업지주']
nine=['고려아연',
 '고려제강',
 '동국제강',
 '동원시스템즈',
 '세아베스틸',
 '영풍',
 '풍산',
 '현대제철',
 'POSCO']
ten = ['넷마블',
 '엔씨소프트',
 '이노션',
 '제일기획',
 '카카오',
 'CJ',
 'CGV',
 'KT',
 'LG유플러스',
 'NAVER',
 'SBS',
 'SK텔레콤']
ele=['녹십자',
 '녹십자홀딩스',
 '대웅제약',
 '동아쏘시오홀딩스',
 '동아에스티',
 '보령제약',
 '부광약품',
 '삼성바이오로직스',
 '셀트리온',
 '영진약품',
 '유한양행',
 '일양약품',
 '종근당',
 '한미사이언스',
 '한미약품',
 '한올바이오파마',
 'JW중외제약',
 'JW홀딩스']

In [219]:
x1=man3[man3['itemname'].isin(one)]
x2=man3[man3['itemname'].isin(two)]
x3=man3[man3['itemname'].isin(three)]
x4=man3[man3['itemname'].isin(four)]
x5=man3[man3['itemname'].isin(five)]
x6=man3[man3['itemname'].isin(six)]
x7=man3[man3['itemname'].isin(seven)]
x8=man3[man3['itemname'].isin(eight)]
x9=man3[man3['itemname'].isin(nine)]
x10=man3[man3['itemname'].isin(ten)]
x11=man3[man3['itemname'].isin(ele)]

In [ ]:
# 기하평균

In [221]:
gmean_1=x1.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_2=x2.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_3=x3.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_4=x4.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_5=x5.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_6=x6.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_7=x7.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_8=x8.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_9=x9.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_10=x10.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100
gmean_11=x11.groupby('date')["change_rate +100"].apply(lambda group: group.product() ** (1 / float(len(group))))-100

In [248]:
product.to_csv('finally.csv')